apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: micro
    spec:
      containers:
        - name: micro
          command: [
		          "./micro web",
		          "--server_address=0.0.0.0:8080",
		          "--broker_address=0.0.0.0:10001"
	        ]
          image: microhq/micro:kubernetes
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: micro-port