// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consignment/consignment.proto

package go_micro_srv_consigment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Consignment struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32    `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	ContainersNumber     int32    `protobuf:"varint,4,opt,name=containers_number,json=containersNumber,proto3" json:"containers_number,omitempty"`
	VesselId             string   `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{0}
}

func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (m *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(m, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainersNumber() int32 {
	if m != nil {
		return m.ContainersNumber
	}
	return 0
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

type Response struct {
	Consigment           *Consignment   `protobuf:"bytes,2,opt,name=consigment,proto3" json:"consigment,omitempty"`
	Consigments          []*Consignment `protobuf:"bytes,3,rep,name=consigments,proto3" json:"consigments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetConsigment() *Consignment {
	if m != nil {
		return m.Consigment
	}
	return nil
}

func (m *Response) GetConsigments() []*Consignment {
	if m != nil {
		return m.Consigments
	}
	return nil
}

func init() {
	proto.RegisterType((*Consignment)(nil), "go.micro.srv.consigment.Consignment")
	proto.RegisterType((*Response)(nil), "go.micro.srv.consigment.Response")
}

func init() {
	proto.RegisterFile("proto/consignment/consignment.proto", fileDescriptor_e5e5ab05dfa973d5)
}

var fileDescriptor_e5e5ab05dfa973d5 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x49, 0xd7, 0x96, 0x76, 0x16, 0xd4, 0xe6, 0xa0, 0x41, 0x2f, 0x6b, 0xf5, 0x50, 0x10,
	0x22, 0xd4, 0x47, 0xa8, 0x08, 0x5e, 0x3c, 0x6c, 0xaf, 0x42, 0x69, 0x93, 0x61, 0x3b, 0xe0, 0x26,
	0x21, 0x89, 0xeb, 0xab, 0x78, 0xf5, 0x4d, 0xc5, 0x54, 0xd9, 0x5c, 0x0a, 0xbd, 0x65, 0xfe, 0xef,
	0x9f, 0xc9, 0xfc, 0x09, 0xdc, 0x3a, 0x6f, 0xa3, 0x7d, 0x50, 0xd6, 0x04, 0x6a, 0x4c, 0x8b, 0x26,
	0xe6, 0x67, 0x99, 0x28, 0xbf, 0x6c, 0xac, 0x6c, 0x49, 0x79, 0x2b, 0x83, 0xef, 0xe4, 0x9e, 0xff,
	0xe2, 0xd9, 0x37, 0x83, 0x72, 0xd9, 0xdb, 0xf9, 0x29, 0x0c, 0x48, 0x0b, 0x56, 0xb1, 0xf9, 0xa4,
	0x1e, 0x90, 0xe6, 0x15, 0x94, 0x1a, 0x83, 0xf2, 0xe4, 0x22, 0x59, 0x23, 0x06, 0x09, 0xe4, 0x12,
	0xbf, 0x80, 0xd1, 0x27, 0x52, 0xb3, 0x8b, 0xa2, 0xa8, 0xd8, 0x7c, 0x58, 0xff, 0x55, 0xfc, 0x1e,
	0xa6, 0xca, 0x9a, 0xb8, 0x21, 0x83, 0x3e, 0xac, 0xcd, 0x47, 0xbb, 0x45, 0x2f, 0x4e, 0x92, 0xe5,
	0xbc, 0x07, 0xaf, 0x49, 0xe7, 0xd7, 0x30, 0xe9, 0x30, 0x04, 0x7c, 0x5f, 0x93, 0x16, 0xc3, 0x74,
	0xc9, 0x78, 0x2f, 0xbc, 0xe8, 0xd9, 0x17, 0x83, 0x71, 0x8d, 0xc1, 0x59, 0x13, 0x90, 0x3f, 0x01,
	0xf4, 0xeb, 0xa7, 0x7d, 0xca, 0xc5, 0x9d, 0x3c, 0x10, 0x4f, 0x66, 0xd1, 0xea, 0xac, 0x8f, 0x3f,
	0x43, 0xd9, 0x57, 0x41, 0x14, 0x55, 0x71, 0xf4, 0x98, 0xbc, 0x71, 0x61, 0xe1, 0x6c, 0xb5, 0x23,
	0xe7, 0xc8, 0x34, 0x2b, 0xf4, 0x1d, 0x29, 0xe4, 0x6f, 0x30, 0x5d, 0x7a, 0xdc, 0x44, 0xcc, 0x9f,
	0xf5, 0xa8, 0xd1, 0x57, 0x37, 0x07, 0x5d, 0xff, 0xf1, 0xb7, 0xa3, 0xf4, 0x9f, 0x8f, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x1a, 0xd2, 0xfd, 0x2e, 0xf6, 0x01, 0x00, 0x00,
}
